### PR TITLE
fix(forms): font color does not match

### LINKED ISSUE #325: Komponenten FormView er ikke konsistent med fargevalg
### What happened?

Komponenten FormView med prop `disabled={true}` har ved noen felter helt hvit tekst, mens andre felter har grå tekst.
Forventet resultat er at all tekst har en grå farge.
Skjermbilde 2022-01-09 kl  12 55 42

### What browsers are you seeing the problem on?

Chrome

### What device are you seeing the problem om?

PC

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by MinhdanNg**
## Description
Fargeteksten matcher ikke når disabled=true

closes #325

Changes: Nå er fargen lik

Screenshots:
image

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The PR includes a `closes #issueID`
- [ ] The PR includes a picture showing visual changes
- [ ] Added Google Analytics tracking if relevant
- [ ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

### CODE REVIEW

File: src/components/forms/FieldView.tsx [hunk 1]
```diff
@@ -16,7 +17,7 @@ const FieldView = <FormValues extends FieldValues>({ register, field, formState,
     <input {...register(`answers.${index}.field.id` as Path<FormValues>)} type='hidden' value={field.id} />
     {field.type === FormFieldType.TEXT_ANSWER ? (
       <>
-        {`${field.title} ${field.required ? '*' : ''}`}
+        <Typography style={{ color: disabled ? 'grey' : 'theme.palette.text.secondary' }}>{`${field.title} ${field.required ? '*' : ''}`}</Typography>
```
Comment (olros) [inline src/components/forms/FieldView.tsx:20]: For å bruke `theme` må du bruke `sx`-prop'en og funksjon:
```suggestion
        <Typography sx={{ color: (theme) => theme.palette.text[disabled ? 'disabled' : 'primary'] }}>{`${field.title} ${field.required ? '*' : ''}`}</Typography>
```

**Review by olros — APPROVED** [review]

**Review by olros — CHANGES_REQUESTED** [review]
Whops, mente request changes

**Review by olros — APPROVED** [review]
